### PR TITLE
Fix skelet

### PR DESCRIPTION
**Pull request by hyp3rion31gr3y**
Attempt to fix `AttributeError: partially initialized module 'opl.skelet' has no attribute 'retry_on_traceback' (most likely due to a circular import)` errors coming from skelet.py

### CODE REVIEW

**Comment by vishalvvr** [comment]
After we merge this PR 
we need to make changes to tally service in iperf. 
https://github.com/search?q=repo%3AAppservices-perfscale%2Fiperf+opl.status_data&type=code

**Comment by jhutar** [comment]
Looks great. Pls fix these linter errors (for now I'm perfectly OK to leave these "Clone found" ones in tests unfixed, but the other ones can be fixed easily I guess).

Did the tests passed (see end of the readme on how to run them)?

**Comment by vishalvvr** [comment]
One humble request, 
Please review and merge https://github.com/redhat-performance/opl/pull/128 PR before.
PR#128 has some linting files changes so if we merge those change first, then this PR(#127) won't have unrelated files to commit :)

**Comment by hyp3rion31gr3y** [comment]
since @jhutar solved this issue, PR is not needed now :)

**Pull request closed without merging**
